AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false 